# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=10000']
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
      - id: mixed-line-ending
        args: [--fix=auto]
      - id: name-tests-test
      - id: no-commit-to-branch
        args: [-b main, -b master]
      - id: pretty-format-json
        args: [--autofix]
      - id: requirements-txt-fixer
      # - id: trailing-whitespace
      #   args: [--autofix, --indent=2 --no-sort-keys]

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.7  # Use the sha / tag you want to point at
    hooks:
      - id: autopep8

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.5
    hooks:
      - id: check-mailmap
      - id: git-check
      - id: git-dirty
      - id: shellcheck
        additional_dependencies: []
      - id: shfmt

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.10
    hooks:
      - id: remove-tabs
        args: ['--whitespaces-count', '2']  # defaults to: 4

#  - repo: https://github.com/Lucas-C/pre-commit-hooks-go
#    rev: v1.0.1
#    hooks:
#      - id: checkmake

  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.2.1
    hooks:
      - id: python-safety-dependencies-check

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.42.1
    hooks:
      - id: golangci-lint

  - repo: git://github.com/detailyang/pre-commit-shell
    rev: v1.0.6
    hooks:
      - id: shell-lint
        args: [--format=json]

  - repo: https://github.com/lovesegfault/beautysh
    rev: v6.1.0
    hooks:
      - id: beautysh

  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.50.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
      - id: terraform_tflint
      - id: terraform_validate
      - id: terragrunt_fmt
      - id: terragrunt_validate
      - id: terraform_tfsec
      - id: checkov

  - repo: https://github.com/ansible-community/ansible-lint
    rev: v5.1.3
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - id: yamllint
        args: [-c, .pre-commit.d/yamllint]

  # - repo: https://github.com/thlorenz/doctoc
  #   rev: v2.0.1
  #   hooks:
  #     - id: doctoc

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.15.1
    hooks:
      - id: gitlint
        args: [--config, .pre-config.d/gitlint]

  - repo: https://github.com/psf/black
    rev: 21.8b0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/IamTheFij/ansible-pre-commit
    rev: v0.1.2
    hooks:
      - id: encryption-check

  - repo: https://github.com/thoughtworks/talisman
    rev: v1.22.0
    hooks:
      - id: talisman-commit
      - id: talisman-push

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8

  # - repo: https://github.com/motet-a/jinjalint
  #   rev: '0.5'
  #   hooks:
  #     - id: jinjalint

  - repo: https://github.com/milin/gitown
    rev: v0.1.7
    hooks:
      - id: gitown
        args: ['--ownership_threshold=25', '--codeowners_filename=CODEOWNERS']  # Optional

  - repo: https://github.com/fortman/pre-commit-prometheus
    rev: v1.2.0
    hooks:
      - id: check-rules
        entry: --entrypoint /bin/promtool prom/prometheus:v2.6.0
        files: >
          (?x)^(
            rules_directory/.*\.yml
          )$
      - id: check-config
        entry: --entrypoint /bin/promtool prom/prometheus:v2.6.0
        files: >
          (?x)^(
            config_directory/.*\.yml
          )$
      # - id: test-rules
      #   entry: --entrypoint /bin/promtool prom/prometheus:v2.18.2
      #   always_run: true
      #   files: >
      #     (?x)^(
      #       unit_test_directory/.*\.yml
      #     )$

  - repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
      - id: isort

  # https://github.com/myint/rstcheck/issues/69
  # - repo: https://github.com/myint/rstcheck
  #   rev: v2.2
  #   hooks:
  #     - id: rstcheck
  #       args: [--report=warning]
  #       additional_dependencies:
  #       - sphinx==2.4.4

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.28.1
    hooks:
      - id: markdownlint
        args: [-c, .pre-commit.d/markdownlintrc]

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.1.1
    hooks:
      - id: nbqa-black
        additional_dependencies: [black==21.8b0]
        args: [--nbqa-mutate]
      - id: nbqa-pyupgrade
        additional_dependencies: [pyupgrade==2.7.3]
        args: [--nbqa-mutate, --py36-plus]
      - id: nbqa-isort
        additional_dependencies: [isort==5.9.3]
        args: [--nbqa-mutate]

  # - repo: https://github.com/PrincetonUniversity/blocklint
  #   rev: v0.2.2
  #   hooks:
  #     - id: blocklint

  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.4.1
    hooks:
      - id: check-github-workflows
      - id: check-github-actions
      - id: check-azure-pipelines
      - id: check-travis
      # - id: check-jsonschema

  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.3
    hooks:
      - id: vulture

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.4.0
    hooks:
      - id: reorder-python-imports

exclude: |
    (?x)(
        ^.idea/|
        ^.vscode/|
        ^cis_benchmarks/|
        ^data/|
        ^housekeeping/|
        ^output/|
        ^plugins/
    )
